import markup from "refractor/lang/markup.js";
import css from "refractor/lang/css.js";
import clike from "refractor/lang/clike.js";
import regex from "refractor/lang/regex.js";
import javascript from "refractor/lang/javascript.js";
import abap from "refractor/lang/abap.js";
import abnf from "refractor/lang/abnf.js";
import actionscript from "refractor/lang/actionscript.js";
import ada from "refractor/lang/ada.js";
import agda from "refractor/lang/agda.js";
import al from "refractor/lang/al.js";
import antlr4 from "refractor/lang/antlr4.js";
import apacheconf from "refractor/lang/apacheconf.js";
import sql from "refractor/lang/sql.js";
import apex from "refractor/lang/apex.js";
import apl from "refractor/lang/apl.js";
import applescript from "refractor/lang/applescript.js";
import aql from "refractor/lang/aql.js";
import c from "refractor/lang/c.js";
import cpp from "refractor/lang/cpp.js";
import arduino from "refractor/lang/arduino.js";
import arff from "refractor/lang/arff.js";
import armasm from "refractor/lang/armasm.js";
import bash from "refractor/lang/bash.js";
import yaml from "refractor/lang/yaml.js";
import markdown from "refractor/lang/markdown.js";
import arturo from "refractor/lang/arturo.js";
import asciidoc from "refractor/lang/asciidoc.js";
import csharp from "refractor/lang/csharp.js";
import aspnet from "refractor/lang/aspnet.js";
import asm6502 from "refractor/lang/asm6502.js";
import asmatmel from "refractor/lang/asmatmel.js";
import autohotkey from "refractor/lang/autohotkey.js";
import autoit from "refractor/lang/autoit.js";
import avisynth from "refractor/lang/avisynth.js";
import avroIdl from "refractor/lang/avro-idl.js";
import awk from "refractor/lang/awk.js";
import basic from "refractor/lang/basic.js";
import batch from "refractor/lang/batch.js";
import bbcode from "refractor/lang/bbcode.js";
import bbj from "refractor/lang/bbj.js";
import bicep from "refractor/lang/bicep.js";
import birb from "refractor/lang/birb.js";
import bison from "refractor/lang/bison.js";
import bnf from "refractor/lang/bnf.js";
import bqn from "refractor/lang/bqn.js";
import brainfuck from "refractor/lang/brainfuck.js";
import brightscript from "refractor/lang/brightscript.js";
import bro from "refractor/lang/bro.js";
import bsl from "refractor/lang/bsl.js";
import cfscript from "refractor/lang/cfscript.js";
import chaiscript from "refractor/lang/chaiscript.js";
import cil from "refractor/lang/cil.js";
import cilkc from "refractor/lang/cilkc.js";
import cilkcpp from "refractor/lang/cilkcpp.js";
import clojure from "refractor/lang/clojure.js";
import cmake from "refractor/lang/cmake.js";
import cobol from "refractor/lang/cobol.js";
import coffeescript from "refractor/lang/coffeescript.js";
import concurnas from "refractor/lang/concurnas.js";
import csp from "refractor/lang/csp.js";
import cooklang from "refractor/lang/cooklang.js";
import coq from "refractor/lang/coq.js";
import ruby from "refractor/lang/ruby.js";
import crystal from "refractor/lang/crystal.js";
import cssExtras from "refractor/lang/css-extras.js";
import csv from "refractor/lang/csv.js";
import cue from "refractor/lang/cue.js";
import cypher from "refractor/lang/cypher.js";
import d from "refractor/lang/d.js";
import dart from "refractor/lang/dart.js";
import dataweave from "refractor/lang/dataweave.js";
import dax from "refractor/lang/dax.js";
import dhall from "refractor/lang/dhall.js";
import diff from "refractor/lang/diff.js";
import markupTemplating from "refractor/lang/markup-templating.js";
import django from "refractor/lang/django.js";
import dnsZoneFile from "refractor/lang/dns-zone-file.js";
import docker from "refractor/lang/docker.js";
import dot from "refractor/lang/dot.js";
import ebnf from "refractor/lang/ebnf.js";
import editorconfig from "refractor/lang/editorconfig.js";
import eiffel from "refractor/lang/eiffel.js";
import ejs from "refractor/lang/ejs.js";
import elixir from "refractor/lang/elixir.js";
import elm from "refractor/lang/elm.js";
import lua from "refractor/lang/lua.js";
import etlua from "refractor/lang/etlua.js";
import erb from "refractor/lang/erb.js";
import erlang from "refractor/lang/erlang.js";
import excelFormula from "refractor/lang/excel-formula.js";
import fsharp from "refractor/lang/fsharp.js";
import factor from "refractor/lang/factor.js";
import $false from "refractor/lang/false.js";
import firestoreSecurityRules from "refractor/lang/firestore-security-rules.js";
import flow from "refractor/lang/flow.js";
import fortran from "refractor/lang/fortran.js";
import ftl from "refractor/lang/ftl.js";
import gml from "refractor/lang/gml.js";
import gap from "refractor/lang/gap.js";
import gcode from "refractor/lang/gcode.js";
import gdscript from "refractor/lang/gdscript.js";
import gedcom from "refractor/lang/gedcom.js";
import gettext from "refractor/lang/gettext.js";
import gherkin from "refractor/lang/gherkin.js";
import git from "refractor/lang/git.js";
import glsl from "refractor/lang/glsl.js";
import gn from "refractor/lang/gn.js";
import linkerScript from "refractor/lang/linker-script.js";
import go from "refractor/lang/go.js";
import goModule from "refractor/lang/go-module.js";
import gradle from "refractor/lang/gradle.js";
import graphql from "refractor/lang/graphql.js";
import groovy from "refractor/lang/groovy.js";
import less from "refractor/lang/less.js";
import scss from "refractor/lang/scss.js";
import textile from "refractor/lang/textile.js";
import haml from "refractor/lang/haml.js";
import handlebars from "refractor/lang/handlebars.js";
import haskell from "refractor/lang/haskell.js";
import haxe from "refractor/lang/haxe.js";
import hcl from "refractor/lang/hcl.js";
import hlsl from "refractor/lang/hlsl.js";
import hoon from "refractor/lang/hoon.js";
import hpkp from "refractor/lang/hpkp.js";
import hsts from "refractor/lang/hsts.js";
import json from "refractor/lang/json.js";
import uri from "refractor/lang/uri.js";
import http from "refractor/lang/http.js";
import ichigojam from "refractor/lang/ichigojam.js";
import icon from "refractor/lang/icon.js";
import icuMessageFormat from "refractor/lang/icu-message-format.js";
import idris from "refractor/lang/idris.js";
import ignore from "refractor/lang/ignore.js";
import inform7 from "refractor/lang/inform7.js";
import ini from "refractor/lang/ini.js";
import io from "refractor/lang/io.js";
import j from "refractor/lang/j.js";
import java from "refractor/lang/java.js";
import php from "refractor/lang/php.js";
import javadoclike from "refractor/lang/javadoclike.js";
import scala from "refractor/lang/scala.js";
import javadoc from "refractor/lang/javadoc.js";
import javastacktrace from "refractor/lang/javastacktrace.js";
import jexl from "refractor/lang/jexl.js";
import jolie from "refractor/lang/jolie.js";
import jq from "refractor/lang/jq.js";
import jsTemplates from "refractor/lang/js-templates.js";
import typescript from "refractor/lang/typescript.js";
import jsdoc from "refractor/lang/jsdoc.js";
import n4js from "refractor/lang/n4js.js";
import jsExtras from "refractor/lang/js-extras.js";
import json5 from "refractor/lang/json5.js";
import jsonp from "refractor/lang/jsonp.js";
import jsstacktrace from "refractor/lang/jsstacktrace.js";
import julia from "refractor/lang/julia.js";
import keepalived from "refractor/lang/keepalived.js";
import keyman from "refractor/lang/keyman.js";
import kotlin from "refractor/lang/kotlin.js";
import kumir from "refractor/lang/kumir.js";
import kusto from "refractor/lang/kusto.js";
import latex from "refractor/lang/latex.js";
import latte from "refractor/lang/latte.js";
import scheme from "refractor/lang/scheme.js";
import lilypond from "refractor/lang/lilypond.js";
import liquid from "refractor/lang/liquid.js";
import lisp from "refractor/lang/lisp.js";
import livescript from "refractor/lang/livescript.js";
import llvm from "refractor/lang/llvm.js";
import log from "refractor/lang/log.js";
import lolcode from "refractor/lang/lolcode.js";
import magma from "refractor/lang/magma.js";
import makefile from "refractor/lang/makefile.js";
import mata from "refractor/lang/mata.js";
import matlab from "refractor/lang/matlab.js";
import maxscript from "refractor/lang/maxscript.js";
import mel from "refractor/lang/mel.js";
import mermaid from "refractor/lang/mermaid.js";
import metafont from "refractor/lang/metafont.js";
import mizar from "refractor/lang/mizar.js";
import mongodb from "refractor/lang/mongodb.js";
import monkey from "refractor/lang/monkey.js";
import moonscript from "refractor/lang/moonscript.js";
import n1ql from "refractor/lang/n1ql.js";
import nand2tetrisHdl from "refractor/lang/nand2tetris-hdl.js";
import naniscript from "refractor/lang/naniscript.js";
import nasm from "refractor/lang/nasm.js";
import neon from "refractor/lang/neon.js";
import nevod from "refractor/lang/nevod.js";
import nginx from "refractor/lang/nginx.js";
import nim from "refractor/lang/nim.js";
import nix from "refractor/lang/nix.js";
import nsis from "refractor/lang/nsis.js";
import objectivec from "refractor/lang/objectivec.js";
import ocaml from "refractor/lang/ocaml.js";
import odin from "refractor/lang/odin.js";
import opencl from "refractor/lang/opencl.js";
import openqasm from "refractor/lang/openqasm.js";
import oz from "refractor/lang/oz.js";
import parigp from "refractor/lang/parigp.js";
import parser from "refractor/lang/parser.js";
import pascal from "refractor/lang/pascal.js";
import pascaligo from "refractor/lang/pascaligo.js";
import psl from "refractor/lang/psl.js";
import pcaxis from "refractor/lang/pcaxis.js";
import peoplecode from "refractor/lang/peoplecode.js";
import perl from "refractor/lang/perl.js";
import phpdoc from "refractor/lang/phpdoc.js";
import phpExtras from "refractor/lang/php-extras.js";
import plantUml from "refractor/lang/plant-uml.js";
import plsql from "refractor/lang/plsql.js";
import powerquery from "refractor/lang/powerquery.js";
import powershell from "refractor/lang/powershell.js";
import processing from "refractor/lang/processing.js";
import prolog from "refractor/lang/prolog.js";
import promql from "refractor/lang/promql.js";
import properties from "refractor/lang/properties.js";
import protobuf from "refractor/lang/protobuf.js";
import stylus from "refractor/lang/stylus.js";
import twig from "refractor/lang/twig.js";
import pug from "refractor/lang/pug.js";
import puppet from "refractor/lang/puppet.js";
import pure from "refractor/lang/pure.js";
import purebasic from "refractor/lang/purebasic.js";
import purescript from "refractor/lang/purescript.js";
import python from "refractor/lang/python.js";
import qsharp from "refractor/lang/qsharp.js";
import q from "refractor/lang/q.js";
import qml from "refractor/lang/qml.js";
import qore from "refractor/lang/qore.js";
import r from "refractor/lang/r.js";
import racket from "refractor/lang/racket.js";
import cshtml from "refractor/lang/cshtml.js";
import jsx from "refractor/lang/jsx.js";
import tsx from "refractor/lang/tsx.js";
import reason from "refractor/lang/reason.js";
import rego from "refractor/lang/rego.js";
import renpy from "refractor/lang/renpy.js";
import rescript from "refractor/lang/rescript.js";
import rest from "refractor/lang/rest.js";
import rip from "refractor/lang/rip.js";
import roboconf from "refractor/lang/roboconf.js";
import robotframework from "refractor/lang/robotframework.js";
import rust from "refractor/lang/rust.js";
import sas from "refractor/lang/sas.js";
import sass from "refractor/lang/sass.js";
import shellSession from "refractor/lang/shell-session.js";
import smali from "refractor/lang/smali.js";
import smalltalk from "refractor/lang/smalltalk.js";
import smarty from "refractor/lang/smarty.js";
import sml from "refractor/lang/sml.js";
import solidity from "refractor/lang/solidity.js";
import solutionFile from "refractor/lang/solution-file.js";
import soy from "refractor/lang/soy.js";
import turtle from "refractor/lang/turtle.js";
import sparql from "refractor/lang/sparql.js";
import splunkSpl from "refractor/lang/splunk-spl.js";
import sqf from "refractor/lang/sqf.js";
import squirrel from "refractor/lang/squirrel.js";
import stan from "refractor/lang/stan.js";
import stata from "refractor/lang/stata.js";
import iecst from "refractor/lang/iecst.js";
import supercollider from "refractor/lang/supercollider.js";
import swift from "refractor/lang/swift.js";
import systemd from "refractor/lang/systemd.js";
import t4Templating from "refractor/lang/t4-templating.js";
import t4Cs from "refractor/lang/t4-cs.js";
import vbnet from "refractor/lang/vbnet.js";
import t4Vb from "refractor/lang/t4-vb.js";
import tap from "refractor/lang/tap.js";
import tcl from "refractor/lang/tcl.js";
import tt2 from "refractor/lang/tt2.js";
import toml from "refractor/lang/toml.js";
import tremor from "refractor/lang/tremor.js";
import typoscript from "refractor/lang/typoscript.js";
import unrealscript from "refractor/lang/unrealscript.js";
import uorazor from "refractor/lang/uorazor.js";
import v from "refractor/lang/v.js";
import vala from "refractor/lang/vala.js";
import velocity from "refractor/lang/velocity.js";
import verilog from "refractor/lang/verilog.js";
import vhdl from "refractor/lang/vhdl.js";
import vim from "refractor/lang/vim.js";
import visualBasic from "refractor/lang/visual-basic.js";
import warpscript from "refractor/lang/warpscript.js";
import wasm from "refractor/lang/wasm.js";
import webIdl from "refractor/lang/web-idl.js";
import wgsl from "refractor/lang/wgsl.js";
import wiki from "refractor/lang/wiki.js";
import wolfram from "refractor/lang/wolfram.js";
import wren from "refractor/lang/wren.js";
import xeora from "refractor/lang/xeora.js";
import xmlDoc from "refractor/lang/xml-doc.js";
import xojo from "refractor/lang/xojo.js";
import xquery from "refractor/lang/xquery.js";
import yang from "refractor/lang/yang.js";
import zig from "refractor/lang/zig.js";

export const registerLanguages = (refractor) => {
    refractor.register(markup);
    refractor.register(css);
    refractor.register(clike);
    refractor.register(regex);

    refractor.register(javascript);
    refractor.register(abap);

    refractor.register(abnf);
    refractor.register(actionscript);
    refractor.register(ada);
    refractor.register(agda);
    refractor.register(al);
    refractor.register(antlr4);
    refractor.register(apacheconf);
    refractor.register(sql);
    refractor.register(apex);
    refractor.register(apl);
    refractor.register(applescript);
    refractor.register(aql);
    refractor.register(c);
    refractor.register(cpp);
    refractor.register(arduino);
    refractor.register(arff);
    refractor.register(armasm);
    refractor.register(bash);
    refractor.register(yaml);
    refractor.register(markdown);
    refractor.register(arturo);
    refractor.register(asciidoc);
    refractor.register(csharp);
    refractor.register(aspnet);
    refractor.register(asm6502);
    refractor.register(asmatmel);
    refractor.register(autohotkey);
    refractor.register(autoit);
    refractor.register(avisynth);
    refractor.register(avroIdl);
    refractor.register(awk);
    refractor.register(basic);
    refractor.register(batch);
    refractor.register(bbcode);
    refractor.register(bbj);
    refractor.register(bicep);
    refractor.register(birb);
    refractor.register(bison);
    refractor.register(bnf);
    refractor.register(bqn);
    refractor.register(brainfuck);
    refractor.register(brightscript);
    refractor.register(bro);
    refractor.register(bsl);

    refractor.register(cfscript);
    refractor.register(chaiscript);
    refractor.register(cil);
    refractor.register(cilkc);
    refractor.register(cilkcpp);
    refractor.register(clojure);
    refractor.register(cmake);
    refractor.register(cobol);
    refractor.register(coffeescript);
    refractor.register(concurnas);
    refractor.register(csp);
    refractor.register(cooklang);
    refractor.register(coq);
    refractor.register(ruby);
    refractor.register(crystal);
    refractor.register(cssExtras);
    refractor.register(csv);
    refractor.register(cue);
    refractor.register(cypher);
    refractor.register(d);
    refractor.register(dart);
    refractor.register(dataweave);
    refractor.register(dax);
    refractor.register(dhall);
    refractor.register(diff);
    refractor.register(markupTemplating);
    refractor.register(django);
    refractor.register(dnsZoneFile);
    refractor.register(docker);
    refractor.register(dot);
    refractor.register(ebnf);
    refractor.register(editorconfig);
    refractor.register(eiffel);
    refractor.register(ejs);
    refractor.register(elixir);
    refractor.register(elm);
    refractor.register(lua);
    refractor.register(etlua);
    refractor.register(erb);
    refractor.register(erlang);
    refractor.register(excelFormula);
    refractor.register(fsharp);
    refractor.register(factor);
    refractor.register($false);
    refractor.register(firestoreSecurityRules);
    refractor.register(flow);
    refractor.register(fortran);
    refractor.register(ftl);
    refractor.register(gml);
    refractor.register(gap);
    refractor.register(gcode);
    refractor.register(gdscript);
    refractor.register(gedcom);
    refractor.register(gettext);
    refractor.register(gherkin);
    refractor.register(git);
    refractor.register(glsl);
    refractor.register(gn);
    refractor.register(linkerScript);
    refractor.register(go);

    refractor.register(goModule);
    refractor.register(gradle);
    refractor.register(graphql);
    refractor.register(groovy);
    refractor.register(less);
    refractor.register(scss);
    refractor.register(textile);
    refractor.register(haml);
    refractor.register(handlebars);
    refractor.register(haskell);
    refractor.register(haxe);
    refractor.register(hcl);
    refractor.register(hlsl);
    refractor.register(hoon);
    refractor.register(hpkp);
    refractor.register(hsts);
    refractor.register(json);
    refractor.register(uri);
    refractor.register(http);
    refractor.register(ichigojam);
    refractor.register(icon);
    refractor.register(icuMessageFormat);
    refractor.register(idris);
    refractor.register(ignore);
    refractor.register(inform7);
    refractor.register(ini);
    refractor.register(io);
    refractor.register(j);
    refractor.register(java);

    refractor.register(php);
    refractor.register(javadoclike);
    refractor.register(scala);
    refractor.register(javadoc);
    refractor.register(javastacktrace);
    refractor.register(jexl);
    refractor.register(jolie);
    refractor.register(jq);

    //refractor.register(jsTemplates);
    refractor.register(typescript);

    refractor.register(jsdoc);
    refractor.register(n4js);
    refractor.register(jsExtras);
    refractor.register(json5);
    refractor.register(jsonp);
    refractor.register(jsstacktrace);
    refractor.register(julia);
    refractor.register(keepalived);
    refractor.register(keyman);
    refractor.register(kotlin);
    refractor.register(kumir);
    refractor.register(kusto);

    refractor.register(latex);
    refractor.register(latte);
    refractor.register(scheme);
    refractor.register(lilypond);
    refractor.register(liquid);
    refractor.register(lisp);
    refractor.register(livescript);
    refractor.register(llvm);
    refractor.register(log);
    refractor.register(lolcode);
    refractor.register(magma);
    refractor.register(makefile);
    refractor.register(mata);
    refractor.register(matlab);
    refractor.register(maxscript);
    refractor.register(mel);

    refractor.register(mermaid);
    refractor.register(metafont);
    refractor.register(mizar);
    refractor.register(mongodb);
    refractor.register(monkey);
    refractor.register(moonscript);
    refractor.register(n1ql);
    refractor.register(nand2tetrisHdl);
    refractor.register(naniscript);
    refractor.register(nasm);
    refractor.register(neon);
    refractor.register(nevod);
    refractor.register(nginx);
    refractor.register(nim);
    refractor.register(nix);
    refractor.register(nsis);
    refractor.register(objectivec);
    refractor.register(ocaml);
    refractor.register(odin);

    refractor.register(opencl);
    refractor.register(openqasm);
    refractor.register(oz);
    refractor.register(parigp);
    refractor.register(parser);
    refractor.register(pascal);
    refractor.register(pascaligo);
    refractor.register(psl);
    refractor.register(pcaxis);
    refractor.register(peoplecode);
    refractor.register(perl);
    refractor.register(phpdoc);
    refractor.register(phpExtras);
    refractor.register(plantUml);
    refractor.register(plsql);
    refractor.register(powerquery);
    refractor.register(powershell);
    refractor.register(processing);
    refractor.register(prolog);
    refractor.register(promql);
    refractor.register(properties);
    refractor.register(protobuf);
    refractor.register(stylus);
    refractor.register(twig);
    refractor.register(pug);
    refractor.register(puppet);
    refractor.register(pure);
    refractor.register(purebasic);
    refractor.register(purescript);
    refractor.register(python);
    refractor.register(qsharp);
    refractor.register(q);
    refractor.register(qml);
    refractor.register(qore);
    refractor.register(r);
    refractor.register(racket);
    refractor.register(cshtml);
    refractor.register(jsx);
    refractor.register(tsx);
    refractor.register(reason);
    refractor.register(rego);
    refractor.register(renpy);

    refractor.register(rescript);
    refractor.register(rest);
    refractor.register(rip);
    refractor.register(roboconf);
    refractor.register(robotframework);
    refractor.register(rust);
    refractor.register(sas);
    refractor.register(sass);
    refractor.register(shellSession);
    refractor.register(smali);
    refractor.register(smalltalk);
    refractor.register(smarty);
    refractor.register(sml);
    refractor.register(solidity);
    refractor.register(solutionFile);
    refractor.register(soy);
    refractor.register(turtle);
    refractor.register(sparql);
    refractor.register(splunkSpl);
    refractor.register(sqf);
    refractor.register(squirrel);
    refractor.register(stan);
    refractor.register(stata);
    refractor.register(iecst);
    refractor.register(supercollider);
    refractor.register(swift);
    refractor.register(systemd);
    refractor.register(t4Templating);
    refractor.register(t4Cs);
    refractor.register(vbnet);
    refractor.register(t4Vb);
    refractor.register(tap);
    refractor.register(tcl);
    refractor.register(tt2);
    refractor.register(toml);
    refractor.register(tremor);

    refractor.register(typoscript);

    refractor.register(unrealscript);
    refractor.register(uorazor);
    refractor.register(v);
    refractor.register(vala);
    refractor.register(velocity);
    refractor.register(verilog);
    refractor.register(vhdl);
    refractor.register(vim);
    refractor.register(visualBasic);
    refractor.register(warpscript);
    refractor.register(wasm);
    refractor.register(webIdl);
    refractor.register(wgsl);
    refractor.register(wiki);
    refractor.register(wolfram);
    refractor.register(wren);
    refractor.register(xeora);
    refractor.register(xmlDoc);
    refractor.register(xojo);
    refractor.register(xquery);
    refractor.register(yang);
    refractor.register(zig);
};
